export const propertyStatus = [
  {
    key: "all",
    label: "All",
    variant: "primary",
  },
  {
    key: "for_rent",
    label: "For Rent",
    variant: "outline",
  },
  {
    key: "for_sale",
    label: "For Sale",
    variant: "outline",
  },
  {
    key: "apartment",
    label: "Apartment",
    variant: "outline",
  },
  {
    key: "office",
    label: "Office",
    variant: "outline",
  },
  {
    key: "shop",
    label: "Shop",
    variant: "outline",
  },
];

export const propertyDetails = [
  {
    id: 1,
    propertyImage: "/images/property-1.png",
    propertyName: "Palm Crest Villa",
    location: "Palm Canyon Dr, Palm Springs, CA 92262, USA",
    date: "Added November 21 , 2025",
    agentImage: "/images/agent-1.jpg",
    agentName: "Josh Milner",
    price: "$1,200,000",
    category: "for_sale",
  },

  {
    id: 2,
    propertyImage: "/images/property-2.png",
    propertyName: "Harborview Apartment Suites",
    location: "Collins St, Melbourne VIC 3000, Australia",
    date: "Added November 18 , 2025",
    agentImage: "/images/agent-2.jpg",
    agentName: "Emily Haris",
    price: "$400,000",
    category: "for_rent",
  },

  {
    id: 3,
    propertyImage: "/images/property-3.png",
    propertyName: "Skyline Executive Offices",
    location: " Wacker Dr, Chicago, IL 60606, USA",
    date: "Added November 20 , 2025",
    agentImage: "/images/agent-3.jpg",
    agentName: "Jane Rogers",
    price: "$450,000",
    category: "office",
  },

  {
    id: 4,
    propertyImage: "/images/property-4.png",
    propertyName: "Ocean Breeze Penthouse",
    location: "Waterfront Pl, Seattle, WA 98121, USA",
    date: "Added November 17, 2025",
    agentImage: "/images/agent-4.png",
    agentName: "Alexia Foster ",
    price: "$350,000",
    category: "for_sale",
  },

  {
    id: 5,
    propertyImage: "/images/property-5.png",
    propertyName: "Snowcap Alpine Lodge",
    location: " Snowcap Ln, Aspen, CO 81611, USA",
    date: "Added November 21 , 2025",
    agentImage: "/images/agent-5.jpg",
    agentName: "Michael Hart",
    price: "$650,000",
    category: "for_rent",
  },

  {
    id: 6,
    propertyImage: "/images/property-6.png",
    propertyName: "Celestial Ridge Villa",
    location: " Skyline Dr, Beverly Hills, CA 90210, USA",
    date: "Added November 21 , 2025",
    agentImage: "/images/agent-6.jpg",
    agentName: "Wayne Justin",
    price: "$800,000",
    category: "for_sale",
  },
  {
    id: 7,
    propertyImage: "/images/apartment-1.jpg",
    propertyName: "Golden Horizon Residences",
    location: "Sunset Blvd, Los Angeles, CA 90028, USA",
    date: "Added November 22 , 2025",
    agentImage: "/images/agent-7.jpg",
    agentName: "Daniel Morris",
    price: "$720,000",
    category: "apartment",
  },
  {
    id: 8,
    propertyImage: "/images/lakeside-1.jpg",
    propertyName: "Lakeside Serenity House",
    location: "Lake Shore Dr, Chicago, IL 60611, USA",
    date: "Added November 23 , 2025",
    agentImage: "/images/agent-8.jpg",
    agentName: "Sophia Williams",
    price: "$510,000",
    category: "for_sale",
  },
  {
    id: 9,
    propertyImage: "/images/office-6.jpg",
    propertyName: "Urban Loft Studios",
    location: "Broadway, New York, NY 10012, USA",
    date: "Added November 25 , 2025",
    agentImage: "/images/agent-9.jpg",
    agentName: "Liam Anderson",
    price: "$380,000",
    category: "office",
  },
  {
    id: 10,
    propertyImage: "/images/garden-2.jpg",
    propertyName: "Emerald Garden Villas",
    location: "Greenwood Ave, Seattle, WA 98103, USA",
    date: "Added November 26 , 2025",
    agentImage: "/images/agent-11.jpg",
    agentName: "Olivia Martinez",
    price: "$920,000",
    category: "for_sale",
  },
  {
    id: 11,
    propertyImage: "/images/shop-2.jpg",
    propertyName: "Metro Business Hub",
    location: "Market St, San Francisco, CA 94103, USA",
    date: "Added November 27 , 2025",
    agentImage: "/images/agent-10.jpg",
    agentName: "Ethan Clark",
    price: "$1,050,000",
    category: "shop",
  },
  {
    id: 12,
    propertyImage: "/images/apartment-5.jpg",
    propertyName: "Crystal Bay Apartments",
    location: "Biscayne Blvd, Miami, FL 33132, USA",
    date: "Added November 28 , 2025",
    agentImage: "/images/agent-12.jpg",
    agentName: "Ava Thompson",
    price: "$470,000",
    category: "for_rent",
  },
  {
  id: 13,
  propertyImage: "/images/apartment-3.jpg",
  propertyName: "Sunrise Harbor Apartments",
  location: "Ocean Dr, Miami Beach, FL 33139, USA",
  date: "Added December 1 , 2025",
  agentImage: "/images/agent-1.jpg",
  agentName: "Ryan Cooper",
  price: "$2,500 /month",
  category: "apartment",
},
{
  id: 14,
  propertyImage: "/images/flat-2.jpg",
  propertyName: "Downtown City Flats",
  location: "Main St, Dallas, TX 75201, USA",
  date: "Added December 2 , 2025",
  agentImage: "/images/agent-8.jpg",
  agentName: "Natalie Green",
  price: "$1,900 /month",
  category: "for_rent",
},
{
  id: 15,
  propertyImage: "/images/luxury-1.jpg",
  propertyName: "Riverfront Luxury Suites",
  location: "Riverwalk Blvd, San Antonio, TX 78205, USA",
  date: "Added December 3 , 2025",
  agentImage: "/images/agent-10.jpg",
  agentName: "Kevin White",
  price: "$2,300 /month",
  category: "for_rent",
},

{
  id: 16,
  propertyImage: "/images/apartment-2.jpg",
  propertyName: "Grand City Apartments",
  location: "Madison Ave, New York, NY 10010, USA",
  date: "Added December 4 , 2025",
  agentImage: "/images/agent-4.jpg",
  agentName: "Sophia Turner",
  price: "$600,000",
  category: "apartment",
},
{
  id: 17,
  propertyImage: "/images/apartment-4.jpg",
  propertyName: "Lakeview Modern Apartments",
  location: "Lakeview Dr, Austin, TX 73301, USA",
  date: "Added December 5 , 2025",
  agentImage: "/images/agent-1.jpg",
  agentName: "Jacob Miller",
  price: "$540,000",
  category: "apartment",
},

{
  id: 18,
  propertyImage: "/images/office-1.jpg",
  propertyName: "Tech Valley Office Park",
  location: "Innovation Way, San Jose, CA 95110, USA",
  date: "Added December 6 , 2025",
  agentImage: "/images/agent-2.jpg",
  agentName: "Emma Brooks",
  price: "$1,300,000",
  category: "office",
},
{
  id: 19,
  propertyImage: "/images/office-3.jpg",
  propertyName: "Corporate Tower Suites",
  location: "Wall St, New York, NY 10005, USA",
  date: "Added December 7 , 2025",
  agentImage: "/images/agent-6.jpg",
  agentName: "William Scott",
  price: "$1,750,000",
  category: "office",
},
{
  id: 20,
  propertyImage: "/images/office-4.jpg",
  propertyName: "Plaza Executive Offices",
  location: "Wilshire Blvd, Los Angeles, CA 90010, USA",
  date: "Added December 8 , 2025",
  agentImage: "/images/agent-4.png",
  agentName: "Grace Adams",
  price: "$1,420,000",
  category: "office",
},
{
  id: 21,
  propertyImage: "/images/office-5.jpg",
  propertyName: "Downtown Business Center",
  location: "Peachtree St, Atlanta, GA 30303, USA",
  date: "Added December 9 , 2025",
  agentImage: "/images/agent-10.jpg",
  agentName: "Daniel Carter",
  price: "$1,100,000",
  category: "office",
},

{
  id: 22,
  propertyImage: "/images/shop-4.jpg",
  propertyName: "Central Market Retail Plaza",
  location: "5th Ave, New York, NY 10011, USA",
  date: "Added December 10 , 2025",
  agentImage: "/images/agent-8.jpg",
  agentName: "Olivia Parker",
  price: "$980,000",
  category: "shop",
},
{
  id: 23,
  propertyImage: "/images/shop-3.jpg",
  propertyName: "Downtown Retail Hub",
  location: "King St, Toronto, ON M5H 1A1, Canada",
  date: "Added December 11, 2025",
  agentImage: "/images/agent-11.jpg",
  agentName: "Mia Johnson",
  price: "$1,200,000",
  category: "shop",
},
{
  id: 24,
  propertyImage: "/images/shop-1.jpg",
  propertyName: "Central Plaza Shops",
  location: "Queen St, Sydney, NSW 2000, Australia",
  date: "Added December 12, 2025",
  agentImage: "/images/agent-5.jpg",
  agentName: "Ethan Brown",
  price: "$950,000",
  category: "shop",
}
];

export const howItWorks = [
  {
    id: 1,
    imageUrl: "/images/consultation.png",
    altText: "consultation icon",
    number: "01",
    title: "Consultation",
    description:
      "Schedule a session to discuss your property plans and walk through what comes next",
  },

  {
    id: 2,
    imageUrl: "/images/interior.png",
    altText: "interior icon",
    number: "02",
    title: "Interior Process",
    description:
      "Review your space plans and map out the upcoming interior steps to suit your taste",
  },

  {
    id: 3,
    imageUrl: "/images/walkthrough.png",
    altText: "walkthrough icon",
    number: "03",
    title: "Final Walkthrough",
    description:
      "Review your finished property and ensure everything meets your expectations.",
  },
];

export const faqs = [
  {
    id: 1,

    question: "How do I search for properties on your website?",
    description:
      "To find your dream ? Use our intuitive search bar on our homepage. You can filter by location, pricing range, property type and more. ",
  },
  {
    id: 2,
    question: "How long does it take to close on a property?",
    description: "Closing times can vary, but most properties finalize within 30–60 days. Factors like financing, inspections, and paperwork can affect the timeline.",
  },
  {
    id: 3,
    question: "What is the process for selling a property?",
    description: "Selling your property is simple! List your home with us, set your price, and connect with buyers. We guide you through offers, negotiations, and finalizing the sale.",
  },
  {
    id: 4,
    question: "Can i find other properties not shown online?",
    description: "Yes! Some listings aren’t online. Contact our team directly to access off-market properties and get exclusive opportunities before they appear on the site.",
  },
];

export const testimonialDetails = [
  {
    id: 1,
    image: "/images/testimonial-img1.png",
    message:
      "Discovering my dream home with Nala Homes was effortless. With their user-friendly interface and transparent process made it a stress-free experience. I highly recommend Nala Homes for anyone on a house-hunting journey.",
    name: "Mr & Mrs Gibbs-White",
    rating: 5,
  },
  {
    id: 2,
    image: "/images/testimonial-img2.jpg",
    message:
      "Our home sold faster than we ever expected and even above the asking price. The strategy, communication, and attention to detail from the team were outstanding. We felt supported and informed the entire way.",
    name: "Jason Martins",
    rating: 4,
  },
  {
    id: 3,
    image: "/images/testimonial-img3.jpg",
    message:
      "From browsing to closing, Nala Homes delivered a smooth experience. The intuitive design and clear information saved time and removed uncertainty during every step of my journey as a home buyer today.",
    name: "The Richards Family",
    rating: 5,
  },
  {
    id: 4,
    image: "/images/testimonial-img4.jpg",
    message:
      "Nala Homes truly understands what buyers need. The platform is simple, informative, and trustworthy, making it easy to find the right home without unnecessary pressure at every stage of the journey process.",
    name: "Jennifer Torres",
    rating: 5,
  },
  {
    id: 5,
    image: "/images/testimonial-img5.jpg",
    message:
      "Nala Homes made the entire home search feel effortless. The website is easy to use, transparent, and reliable, giving me confidence and peace of mind throughout the process from start to finish. Highly reccomend",
    name: "Mr & Mrs Rogers",
    rating: 5,
  },
];
